global using DotNet_EventSourcing.ProductMicroservice.Configurations;
global using DotNet_EventSourcing.ProductMicroservice.Entities;
global using DotNet_EventSourcing.ProductMicroservice.Persistence.Base;
global using DotNet_EventSourcing.ProductMicroservice.Services.RabbitMQ;
global using DotNet_EventSourcing.ProductMicroservice.Utils;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using DotNet_EventSourcing.ProductMicroservice.Features.Product.CreateProduct;
